version: 2
updates:
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 99
  reviewers:
  - AravindVNair99
  assignees:
  - AravindVNair99
  ignore:
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.24.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 5.0.0
